### ISSUE TITLE
Make Hadoop version configurable

### ISSUE THREAD

**Issue by gczsjdy** [zjf2012/daos#33]
Currently we hardcoded required hadoop version to 2.7.6. We should be able to indicate this version at compile time.

**Comment by zjf2012** [comment]
As a release, we must have a concrete Hadoop version provided.  Hadoop DAOS should work with any Hadoop version 2.7.x at run time. Please double-check.

**Comment by gczsjdy** [comment]
If you compile against Hadoop 2.7.6, and the Hadoop at runtime is 2.7.3, there will be a `NoClassDefFoundError`. You should compile againt Hadoop 2.7.3, but now it is hardcoded in pom.xml

**Comment by zjf2012** [comment]
let me check

**Comment by zjf2012** [comment]
reproduced and fixed in no_length_check branch
